name: SCP transcfer files to EC2

on:
  push:

jobs:
  scpupload:
    runs-on: ubuntu-latest

    steps:
      #このymlが使われるリポジトリをチェックアウトします
      - name: Checkout repository
        uses: actions/checkout@v3
      #チェックアウトしたリポジトリ内のtest-vue-app/index.htmlをEC2の/tmpにアップロードします
      - name: Upload files by SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASS }}
          source: "test-vue-app/README.md"
          target: "/tmp"